# Enable 256 color mode
set -g default-terminal "screen-256color"

# Enable 24-bit (true) color support
set -g terminal-overrides 'xterm-256color:Tc'

# Allow tmux to send true color support to applications
set -g default-terminal "screen-256color"
